// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMyC1ABDWMOSyYQWORKCnvF8GkAOCfiNs',
    appId: '1:961107115509:web:66d1cd9ad3f9a2e2b434bc',
    messagingSenderId: '961107115509',
    projectId: 'blog-a4f42',
    authDomain: 'blog-a4f42.firebaseapp.com',
    storageBucket: 'blog-a4f42.firebasestorage.app',
    measurementId: 'G-3JK8MW84SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6EBu9bM87nOPFMZ-czC56iAGC3-ai5xU',
    appId: '1:961107115509:android:ff5c45f21556c08bb434bc',
    messagingSenderId: '961107115509',
    projectId: 'blog-a4f42',
    storageBucket: 'blog-a4f42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbCR_fyFEoHBAbSO6bv6ppx3pQXoyOC8I',
    appId: '1:961107115509:ios:9d5282a61c17bb33b434bc',
    messagingSenderId: '961107115509',
    projectId: 'blog-a4f42',
    storageBucket: 'blog-a4f42.firebasestorage.app',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbCR_fyFEoHBAbSO6bv6ppx3pQXoyOC8I',
    appId: '1:961107115509:ios:9d5282a61c17bb33b434bc',
    messagingSenderId: '961107115509',
    projectId: 'blog-a4f42',
    storageBucket: 'blog-a4f42.firebasestorage.app',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMyC1ABDWMOSyYQWORKCnvF8GkAOCfiNs',
    appId: '1:961107115509:web:92d11204580a3d53b434bc',
    messagingSenderId: '961107115509',
    projectId: 'blog-a4f42',
    authDomain: 'blog-a4f42.firebaseapp.com',
    storageBucket: 'blog-a4f42.firebasestorage.app',
    measurementId: 'G-57N9WTYRBZ',
  );

}